### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by riban-bw** [OpenMusicKontrollers/osc.lv2#1]
I downloaded and built the project hoping to use it to interface OSC with existing LV2 plugins but am left wondering how to use it. The README only informs how to build. It would be advantageous to have a description of what this does and how to use it.

**Comment by ventosus** [comment]
This has no use of its own, it is a header-only library to be embedded as a subproject into other projects. This is intended for developers of LV2 plugins, not users. I figure you are the latter.

Not sure what you're looking for exactly, but eteroj [1] and moony [2] LV2 plugins both make use of this and may be of use to you.

[1] https://open-music-kontrollers.ch/lv2/eteroj/
[2] https://open-music-kontrollers.ch/lv2/moony/

**Comment by riban-bw** [comment]
I am a developer working on Zynthian project. I am looking for a method to control LV2 parameters via OSC. The intention is to provide a generic mechanism for using OSC to control any LV2 plugin. I will read the resources you referenced. I would recommend adding to your README a description of the library"s purpose and how to integrate with other code. Cheers!

**Comment by ventosus** [comment]
> I am a developer working on Zynthian project. I am looking for a method to control LV2 parameters via OSC. The intention is to provide a generic mechanism for using OSC to control any LV2 plugin.

OK, it was not clear at all what you were looking for and I cannot read minds, sorry for the confusion.

> I will read the resources you referenced.

This lib is mainly about serializing/deserializing raw OSC to/from LV2 Atom events, in order to be able to route them between plugins (like MIDI). E.g. the library mainly is for plugin developers, not host developers. It has no notion of lv2:Parameter, that's the host's job to map MIDI/OSC to parameters, this library won't help you in this regard (but stream.h).

You seem to want to do the equivalent to MIDI-learn, just with OSC, I guess?  Well, there's no magic involved there: Run an OSC server in zynthian and come up with some static OSC path-mappings (or offer OSC-learn) for all plugins in the graph.

Disclaimer: I don't know how zynthian works, so I may make totally wrong assumptions.

This lib contains an minimal OSC server (stream.h) without any dependencies, but most other hosts that support OSC use liblo [1].

> I would recommend adding to your README a description of the library"s purpose and how to integrate with other code. 

Well, I'm its sole user so far, so it was not needed until now :-)

I'll repoen the issue for now

[1] http://liblo.sourceforge.net/

**Comment by ventosus** [comment]
I'm pretty sure I can help you, e.g. hint you in the right direction, as I am both LV2 plugin + host author and knowledgeable in LV2s event system. But in order to help, I would need to know exactly what you're trying to do (and how zynthian works under the hood).
